version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  # build:
  #   docker:
  #     - image: cimg/ruby:2.7-node
  #   steps:
  #     - checkout
  #     - ruby/install-deps
  #     - node/install-packages:
  #       package-mgr: yarn
  #       cache-key: "yarn.lock"

  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: squint-ruby
          POSTGRES_DB: squint_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "1"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: squint-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: gem install bundler:2.0.2 && bundle version
      - run: bundle install
      - run: bundle exec appraisal generate
      - run: bundle exec appraisal install
      - run:
          name: Database setup
          command: bundle exec appraisal rails-5-1-6-2 rake --rakefile test/dummy/Rakefile db:setup --trace
      - run: bundle exec appraisal rake

workflows:
  version: 2
  test:
    jobs:
      - test

